fix nonbinary pronouns
nickmontfort/curveship-js pull request #76
Opened 2022-09-27 16:58 UTC by cjquines

agents with nonbinary gender should be referred to with the nonbinary pronoun set.

in typical english usage this is treated as a plural third-person pronoun ("they sing" rather than "they sings") so we add a method that treats the agent as plural.

didn't test this too hard but it should work

2022-09-28 16:17 UTC, cjquines commented on curveship.js
> +    let isPronoun = this.whatPronoun(subject, spin, "subject", ev);
i believe so—this line checks if pronouns are being used for this event and subject

2022-09-28 17:20 UTC, nickmontfort requested changes
The Missing Names Test in text/nameless now fails.

2022-09-28 17:46 UTC, cjquines commented
my bad—should be fixed. checked all the other tests and edited a test too.

2022-09-29 03:31 UTC, nickmontfort commented
Looks good. I am going to add one line to text/nameless/story.js after approving this so that there is a regression test for your contribution.

2022-09-29 03:31 UTC, merged